version: "3.9"

services:
  nextjs-app:
    container_name: nextjs-app
    build: .
    ports:
      - "5555:5555"
    environment:
      - NODE_ENV=production
    command: npm start -- -p 5555
    volumes:
      - .:/app
      - /app/node_modules
