version: "3.9"

services:
  app:
    container_name: ${CONTAINER_NAME}
    build:
      context: .  # Explicitly set build context
      dockerfile: Dockerfile  # Explicitly point to Dockerfile
    ports:
      - "${APP_PORT}:5555"
    environment:
      - NODE_ENV=production
      - APP_TITLE=${APP_TITLE}
    command: npm start -- -p 5555