version: "3.9"

services:
  app:  # Fixed name - variables only work in values, not keys
    container_name: ${CONTAINER_NAME}  # Variable works here
    build: .
    ports:
      - "${APP_PORT}:5555"
    environment:
      - NODE_ENV=production
      - APP_TITLE=${APP_TITLE}
    command: npm start -- -p 5555