version: "3.9"

services:
  nextjs-app:
    container_name: nextjs-app
    build: .
    ports:
      - "${APP_PORT:-5555}:5555"
    environment:
      - NODE_ENV=production
      - APP_TITLE=${APP_TITLE:-My Dynamic Website}
    command: npm start -- -p 5555
