version: "3.9"

services:
  ${CONTAINER_NAME}:
    container_name: ${CONTAINER_NAME}
    build: .
    ports:
      - "${APP_PORT:-5555}:5555"
    environment:
      - NODE_ENV=production
      - APP_TITLE=${APP_TITLE:-My Dynamic Website}
    command: npm start -- -p 5555
